#! /usr/bin/perl
# a quickie by Jonathan Mayer to generate the strings.h file from a lang file

my @data = <>;
$_ = join("",@data);

s!\/\*.*?\*\/!!gs; # no c comments.

my %hash = ();
my $cnt = 1;
print "/* This file is autogenerated - DO NOT EDIT! */\n\n";
print "#ifndef COMMON_STRINGS_H\n";
print "#define COMMON_STRINGS_H\n";
s!([A-Za-z_0-9]+)\s*=\s*\".*?\"!
        print sprintf("#define %s \t 0x%08x\n", $1, $cnt++);
        "";
!gsex;
print "\n#endif /*__STRINGS_H_*/\n";
# LICENSE:
# This software is subject to the terms of the GNU GENERAL 
# PUBLIC LICENSE Version 2, June 1991
