#!/usr/bin/perl -w
# $Id: buildh.pl,v 1.1.1.1 2003/06/10 22:41:37 iceblink Exp $

use strict;

my @chars = ( 
	'a','b','c','d','e','f','g','h','i','j','k','l','m',
	'n','o','p','q','r','s','t','u','v','w','x','y','z', 
	'A','B','C','D','E','F','G','H','I','J','K','L','M',
	'N','O','P','Q','R','S','T','U','V','W','X','Y','Z' 
);

if ($#ARGV != 0) {
	die "usage: $0 <input_file>\n";
}

my $magic = "";
for (my $i = 0; $i < 16; $i++) {
	$magic .= $chars[int(rand(52))];
}
$magic .= "_H";

open(CONF, "< $ARGV[0]") || die "$!";
print "/* This file is automatically generated - DO NOT EDIT */\n";
print "#ifndef $magic\n";
print "#define $magic\n\n";

while (defined($_ = <CONF>)) {
	my @kv = split(/\s*=\s*/, $_);
	chomp($kv[1]);
	print "#define $kv[0]\t\t $kv[1]\n";
}
print "\n#endif /* $magic */\n";

close(CONF);

# LICENSE:
# This software is subject to the terms of the GNU GENERAL 
# PUBLIC LICENSE Version 2, June 1991
